stages:
  - lint
  - changes
  - validate

workflow:
  rules:
    # allow pipeline triggered by MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

lint:
  image: registry.gitlab.com/centos/integration/containers/tmt:latest
  stage: lint
  script:
    - tmt lint --failed-only
    - find . -name '*.sh' -not -path "*/legacy/*" | xargs -n 1 shellcheck --severity=error --shell=bash

extract-changes:
  stage: changes
  image: docker.io/bitnami/git:latest
  script:
    - git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA | awk -F/ '/tests/ { if ($2 == "legacy") { print "name:/" $1 "/" $2 "/" $3 } else { print "name:/" $1 "/" $2 ".*" } }' | sort -u | awk '{ if (NR > 1) {printf "|" $0 } else { printf $0 } }' > changed-tests-regex.log
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - changed-tests-regex.log

validate-cs9:
  stage: validate
  image: quay.io/testing-farm/cli:latest
  script:
    - |
      testing-farm request \
      --git-ref $CI_MERGE_REQUEST_REF_PATH \
      --git-url $CI_MERGE_REQUEST_PROJECT_URL \
      --context distro=centos-stream-9 \
      --compose CentOS-Stream-9 \
      --test-filter "$(cat changed-tests-regex.log)"

validate-cs10:
  stage: validate
  image: quay.io/testing-farm/cli:latest
  script:
    - |
      testing-farm request \
      --git-ref $CI_MERGE_REQUEST_REF_PATH \
      --git-url $CI_MERGE_REQUEST_PROJECT_URL \
      --context distro=centos-stream-10 \
      --compose CentOS-Stream-10 \
      --test-filter "$(cat changed-tests-regex.log)"
