stages:
  - verify
  - test

workflow:
  rules:
    # allow pipeline triggered by MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

verify:
  image: registry.gitlab.com/centos/integration/containers/tmt:latest
  stage: verify
  script:
    - tmt lint --failed-only
    - find . -name '*.sh' -not -path "*/legacy/*" | xargs -n 1 shellcheck --severity=error --shell=bash

validate-cs9:
  stage: test
  image: quay.io/testing-farm/cli:latest
  when: manual
  script:
    - git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA | awk -F/ '/tests/ { if ($2 == "legacy") { print "name:/" $1 "/" $2 "/" $3 } else { print "name:/" $1 "/" $2 } }' | sort -u | awk '{ if (NR > 1) {printf "|" $0 } else { printf $0 } }' > tests-regex.log
    - echo testing-farm request --git-ref $CI_MERGE_REQUEST_REF_PATH --git-url $CI_MERGE_REQUEST_PROJECT_URL --compose CentOS-Stream-9 --filter "$(cat tests-regex.log)"
